package cl.ricardo.miagenda
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.platform.LocalContext
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import cl.ricardo.miagenda.data.*
import kotlinx.coroutines.launch
import java.util.Date
import java.text.SimpleDateFormat
import java.util.Locale

private val hospitalFmt=SimpleDateFormat("dd/MM/yyyy",Locale("es","CL"))

@Composable fun HospitalHub(dao:AgendaDao){
 val records by dao.hospitalRecords().collectAsStateWithLifecycle(emptyList());val containers by dao.containers().collectAsStateWithLifecycle(emptyList())
 var section by remember{mutableStateOf<String?>(null)}
 if(section!=null){HospitalSection(section!!,records,containers,dao){section=null};return}
 val modules=listOf("Renovación de contratos" to "CONTRACT","Charlas" to "TALK","Inspecciones y levantamientos" to "INSPECTION","Cambio / habilitación de contenedores" to "CONTAINER_CHANGE","Inventario por servicio" to "INVENTORY")
 LazyColumn(Modifier.fillMaxSize().padding(horizontal=20.dp),contentPadding=PaddingValues(vertical=18.dp)){
 item{Text("Hospital",style=MaterialTheme.typography.headlineSmall);Text("Gestión administrativa y operativa",color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(16.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Metric("Registros",records.size);Metric("Contenedores",containers.sumOf{it.quantity});Metric("Pendientes",records.count{it.status!="DONE"})};Spacer(Modifier.height(16.dp))}
 items(modules){m->HorizontalDivider();ListItem(Modifier.clickable{section=m.second},headlineContent={Text(m.first)},trailingContent={Icon(Icons.Outlined.ChevronRight,null)})}
 }}
@Composable private fun Metric(label:String,n:Int){Column{Text(n.toString(),style=MaterialTheme.typography.titleLarge);Text(label,style=MaterialTheme.typography.labelSmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}
@Composable fun HospitalSection(type:String,records:List<HospitalRecord>,containers:List<ContainerAsset>,dao:AgendaDao,back:()->Unit){
 val scope=rememberCoroutineScope();val context=LocalContext.current;var add by remember{mutableStateOf(false)}
 var contractRange by remember{mutableStateOf("Mes")};var contractSearch by remember{mutableStateOf("")};var inventoryLocation by remember{mutableStateOf("")};var talkSearch by remember{mutableStateOf("")};var talkRange by remember{mutableStateOf("Mes")};var inspectionFilter by remember{mutableStateOf("Todos")};var replaceAsset by remember{mutableStateOf<ContainerAsset?>(null)};var selectedRecord by remember{mutableStateOf<HospitalRecord?>(null)}
 val title=when(type){"CONTRACT"->"Contratos";"TALK"->"Charlas";"INSPECTION"->"Inspecciones";"CONTAINER_CHANGE"->"Cambios de contenedor";else->"Inventario por servicio"}
 Column(Modifier.fillMaxSize().padding(20.dp)){Row{IconButton(onClick=back){Icon(Icons.Outlined.ArrowBack,null)};Column{Text(title,style=MaterialTheme.typography.headlineSmall);Text("Hospital",color=MaterialTheme.colorScheme.onSurfaceVariant)}};Spacer(Modifier.height(12.dp))
 if(type=="INVENTORY") InventoryList(containers){replaceAsset=it} else {
 if(type=="TALK"){OutlinedTextField(talkSearch,{talkSearch=it},Modifier.fillMaxWidth(),label={Text("Buscar servicio, tema o lugar")},leadingIcon={Icon(Icons.Outlined.Search,null)});Spacer(Modifier.height(6.dp));LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){items(listOf("Mes","Año","Todos")){v->FilterChip(selected=talkRange==v,onClick={talkRange=v},label={Text(v)})}};Spacer(Modifier.height(8.dp))}
 if(type=="CONTRACT"){OutlinedTextField(contractSearch,{contractSearch=it},Modifier.fillMaxWidth(),label={Text("Buscar funcionario o servicio")},leadingIcon={Icon(Icons.Outlined.Search,null)});Spacer(Modifier.height(6.dp));LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){items(listOf("Mes","Próximo mes","3 meses","Todos")){v->FilterChip(selected=contractRange==v,onClick={contractRange=v},label={Text(v)})}};Spacer(Modifier.height(8.dp))}
 if(type=="INSPECTION"){LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){items(listOf("Todos","Pendiente","En proceso","Vencido","Solucionado")){v->FilterChip(selected=inspectionFilter==v,onClick={inspectionFilter=v},label={Text(v)})}};Spacer(Modifier.height(8.dp))}
 Button(onClick={add=true}){Icon(Icons.Outlined.Add,null);Spacer(Modifier.width(6.dp));Text("Agregar")};Spacer(Modifier.height(8.dp));LazyColumn{items(records.filter{r->r.type==type&&if(type!="CONTRACT")true else {val textOk=contractSearch.isBlank()||r.title.contains(contractSearch,true)||r.service.contains(contractSearch,true);val cal=java.util.Calendar.getInstance();val start=java.util.Calendar.getInstance().apply{set(java.util.Calendar.DAY_OF_MONTH,1);set(java.util.Calendar.HOUR_OF_DAY,0);set(java.util.Calendar.MINUTE,0);set(java.util.Calendar.SECOND,0);set(java.util.Calendar.MILLISECOND,0)};val end=java.util.Calendar.getInstance().apply{timeInMillis=start.timeInMillis;when(contractRange){"Mes"->add(java.util.Calendar.MONTH,1);"Próximo mes"->{add(java.util.Calendar.MONTH,2)};"3 meses"->add(java.util.Calendar.MONTH,3);else->add(java.util.Calendar.YEAR,100)}};val dateOk=when(contractRange){"Próximo mes"->{val next=java.util.Calendar.getInstance().apply{timeInMillis=start.timeInMillis;add(java.util.Calendar.MONTH,1)}.timeInMillis;r.date in next.timeInMillis until end.timeInMillis};"Todos"->true;else->r.date in start.timeInMillis until end.timeInMillis};textOk&&dateOk}&&if(type=="TALK"){val textOk=talkSearch.isBlank()||r.title.contains(talkSearch,true)||r.service.contains(talkSearch,true)||r.location.contains(talkSearch,true);val c=java.util.Calendar.getInstance();val y=c.get(java.util.Calendar.YEAR);val m=c.get(java.util.Calendar.MONTH);val rc=java.util.Calendar.getInstance().apply{timeInMillis=r.date};val dateOk=when(talkRange){"Mes"->rc.get(java.util.Calendar.YEAR)==y&&rc.get(java.util.Calendar.MONTH)==m;"Año"->rc.get(java.util.Calendar.YEAR)==y;else->true};textOk&&dateOk}else true&&if(type=="INSPECTION"){val shown=if(r.status!="SOLVED"&&r.dueAt!=null&&r.dueAt<System.currentTimeMillis())"Vencido" else when(r.status){"IN_PROGRESS"->"En proceso";"SOLVED"->"Solucionado";else->"Pendiente"};inspectionFilter=="Todos"||inspectionFilter==shown}else true}){r->val shownStatus=if(type=="INSPECTION"&&r.status!="SOLVED"&&r.dueAt!=null&&r.dueAt<System.currentTimeMillis())"Vencido" else when(r.status){"IN_PROGRESS"->"En proceso";"SOLVED"->"Solucionado";"ACTIVE"->"Pendiente";else->r.status};HorizontalDivider();ListItem(modifier=Modifier.clickable{if(type=="INSPECTION")selectedRecord=r},headlineContent={Text(r.title)},supportingContent={Text(r.service+(if(r.location.isNotBlank())" · "+r.location else "")+" · "+hospitalFmt.format(Date(r.date)))},trailingContent={Text(shownStatus)})}}}}
 if(replaceAsset!=null&&type=="INVENTORY") ReplaceContainerDialog(replaceAsset!!,{replaceAsset=null}){kind,cap,color,qty,notes->val old=replaceAsset!!;scope.launch{dao.updateContainer(old.copy(active=false));dao.addContainer(ContainerAsset(service=old.service,location=old.location,kind=kind,capacityLiters=cap,color=color,quantity=qty,support=old.support,notes=notes));dao.addHospitalRecord(HospitalRecord(type="CONTAINER_CHANGE",service=old.service,location=old.location,date=System.currentTimeMillis(),title="Cambio: "+old.kind+" → "+kind,detail="Anterior: "+old.quantity+" × "+old.kind+(old.capacityLiters?.let{" "+it+" L"}?:"")+" / Nuevo: "+qty+" × "+kind+(cap?.let{" "+it+" L"}?:"")+(if(notes.isNotBlank())+" · "+notes else ""),status="DONE"))};replaceAsset=null}
 if(selectedRecord!=null&&type=="INSPECTION") InspectionStatusDialog(selectedRecord!!,{selectedRecord=null}){status->scope.launch{dao.updateHospitalRecord(selectedRecord!!.copy(status=status))};selectedRecord=null}
 if(add){if(type=="CONTAINER_CHANGE") ContainerDialog({add=false}){service,loc,kind,liters,color,qty,notes->scope.launch{dao.addContainer(ContainerAsset(service=service,location=loc,kind=kind,capacityLiters=liters,color=color,quantity=qty,notes=notes));dao.addHospitalRecord(HospitalRecord(type=type,service=service,location=loc,date=System.currentTimeMillis(),title="Habilitación: "+kind,detail=notes))};add=false} else if(type=="INSPECTION") InspectionDialog({add=false}){service,loc,kind,finding,responsible,date,due->scope.launch{dao.addHospitalRecord(HospitalRecord(type=type,service=service,location=loc,date=date,title=kind,detail=finding,status="ACTIVE",dueAt=due,responsible=responsible));val ws=dao.findWorkspace("Hospital");if(ws!=null){val id=dao.addTask(Task(workspaceId=ws.id,category="Seguimiento de inspección",title="Resolver: "+kind,detail=service+" · "+responsible,dueAt=due));ReminderWorker.scheduleSequence(context,id,"Seguimiento: "+kind,due,listOf(10080,2880,1440))}};add=false} else SmartRecordDialog(type,{add=false}){service,loc,name,detail,date->scope.launch{dao.addHospitalRecord(HospitalRecord(type=type,service=service,location=loc,date=date,title=name,detail=detail));if(type=="CONTRACT"){val ws=dao.findWorkspace("Hospital");if(ws!=null){val id=dao.addTask(Task(workspaceId=ws.id,category="Renovación de contrato",title="Renovar contrato: "+name,detail=service+(if(detail.isNotBlank())+" · "+detail else ""),dueAt=date));ReminderWorker.scheduleSequence(context,id,"Renovar contrato: "+name,date,listOf(43200,21600,10080,2880))}}};add=false}}
@Composable fun InventoryList(data:List<ContainerAsset>,replace:(ContainerAsset)->Unit){
 var service by remember{mutableStateOf("")};var location by remember{mutableStateOf("")}
 val filtered=data.filter{(service.isBlank()||it.service.contains(service,true))&&(location.isBlank()||it.location.contains(location,true))}
 val groups=filtered.groupBy{it.service}
 Column{OutlinedTextField(service,{service=it},Modifier.fillMaxWidth(),label={Text("Servicio clínico")},leadingIcon={Icon(Icons.Outlined.Search,null)});Spacer(Modifier.height(6.dp));OutlinedTextField(location,{location=it},Modifier.fillMaxWidth(),label={Text("Sala / box / ubicación")});Spacer(Modifier.height(10.dp))
  Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Metric("Servicios",groups.size);Metric("Unidades",filtered.sumOf{it.quantity});Metric("Ubicaciones",filtered.map{it.service+"|"+it.location}.distinct().size)}
  Spacer(Modifier.height(10.dp));LazyColumn{groups.forEach{(name,items)->item{Text(name,style=MaterialTheme.typography.titleMedium,modifier=Modifier.padding(top=12.dp,bottom=4.dp));Text(items.sumOf{it.quantity}.toString()+" contenedores · "+items.map{it.location}.distinct().size+" ubicaciones",style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};items(items){asset->HorizontalDivider();ListItem(modifier=Modifier.clickable{replace(asset)},headlineContent={Text(asset.location)},supportingContent={Text(asset.quantity.toString()+" × "+asset.kind+(asset.capacityLiters?.let{" · "+it+" L"}?:"")+" · "+asset.color+(if(asset.support)" · con soporte" else ""))},trailingContent={Icon(Icons.Outlined.SwapHoriz,null)})}}}
 }
}
@Composable fun SmartRecordDialog(type:String,close:()->Unit,save:(String,String,String,String,Long)->Unit){
 var service by remember{mutableStateOf("")};var location by remember{mutableStateOf("")};var name by remember{mutableStateOf("")};var detail by remember{mutableStateOf("")};var date by remember{mutableLongStateOf(System.currentTimeMillis())};val context=androidx.compose.ui.platform.LocalContext.current
 val labels=when(type){"CONTRACT"->listOf("Servicio / unidad","Cargo o ubicación","Nombre del funcionario","Tipo de contrato / observaciones");"TALK"->listOf("Servicio clínico","Lugar","Tema de la charla","Asistentes / observaciones");else->listOf("Servicio clínico","Sala / box / ubicación","Tipo de inspección","Hallazgos, responsable y seguimiento")}
 AlertDialog(onDismissRequest=close,title={Text(when(type){"CONTRACT"->"Nueva renovación";"TALK"->"Nueva charla";else->"Nueva inspección"})},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){
  OutlinedTextField(service,{service=it},label={Text(labels[0])});OutlinedTextField(location,{location=it},label={Text(labels[1])});OutlinedTextField(name,{name=it},label={Text(labels[2])});OutlinedTextField(detail,{detail=it},label={Text(labels[3])},minLines=2)
  OutlinedButton(onClick={val cal=java.util.Calendar.getInstance().apply{timeInMillis=date};android.app.DatePickerDialog(context,{_,y,m,d->date=java.util.Calendar.getInstance().apply{set(y,m,d,9,0,0)}.timeInMillis},cal.get(java.util.Calendar.YEAR),cal.get(java.util.Calendar.MONTH),cal.get(java.util.Calendar.DAY_OF_MONTH)).show()}){Icon(Icons.Outlined.CalendarMonth,null);Spacer(Modifier.width(6.dp));Text((if(type=="CONTRACT")"Vencimiento: " else "Fecha: ")+hospitalFmt.format(java.util.Date(date)))}
 }},confirmButton={Button(enabled=service.isNotBlank()&&name.isNotBlank(),onClick={save(service,location,name,detail,date)}){Text("Guardar")}},dismissButton={TextButton(onClick=close){Text("Cancelar")}})
}
@Composable fun ContainerDialog(close:()->Unit,save:(String,String,String,Double?,String,Int,String)->Unit){var s by remember{mutableStateOf("")};var l by remember{mutableStateOf("")};var k by remember{mutableStateOf("")};var cap by remember{mutableStateOf("")};var color by remember{mutableStateOf("")};var q by remember{mutableStateOf("1")};var notes by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Habilitar contenedor")},text={Column(verticalArrangement=Arrangement.spacedBy(7.dp)){OutlinedTextField(s,{s=it},label={Text("Servicio")});OutlinedTextField(l,{l=it},label={Text("Sala / box / ubicación")});OutlinedTextField(k,{k=it},label={Text("Tipo de contenedor")});OutlinedTextField(cap,{cap=it},label={Text("Capacidad (L)")});OutlinedTextField(color,{color=it},label={Text("Color")});OutlinedTextField(q,{q=it},label={Text("Cantidad")});OutlinedTextField(notes,{notes=it},label={Text("Observaciones")})}},confirmButton={Button(enabled=s.isNotBlank()&&l.isNotBlank()&&k.isNotBlank(),onClick={save(s,l,k,cap.toDoubleOrNull(),color,q.toIntOrNull()?:1,notes)}){Text("Guardar")}},dismissButton={TextButton(onClick=close){Text("Cancelar")}})}

@Composable fun InspectionStatusDialog(record:HospitalRecord,close:()->Unit,save:(String)->Unit){var status by remember{mutableStateOf(record.status)};AlertDialog(onDismissRequest=close,title={Text(record.title)},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text(record.service+(if(record.location.isNotBlank())" · "+record.location else ""));Text(record.detail.ifBlank{"Sin observaciones"});listOf("ACTIVE" to "Pendiente","IN_PROGRESS" to "En proceso","SOLVED" to "Solucionado").forEach{p->FilterChip(selected=status==p.first,onClick={status=p.first},label={Text(p.second)})}}},confirmButton={Button(onClick={save(status)}){Text("Guardar estado")}},dismissButton={TextButton(onClick=close){Text("Cancelar")}})}

@Composable fun InspectionDialog(close:()->Unit,save:(String,String,String,String,String,Long,Long)->Unit){
 var service by remember{mutableStateOf("")};var location by remember{mutableStateOf("")};var kind by remember{mutableStateOf("")};var finding by remember{mutableStateOf("")};var responsible by remember{mutableStateOf("")};var date by remember{mutableLongStateOf(System.currentTimeMillis())};var due by remember{mutableLongStateOf(System.currentTimeMillis()+7*86400000L)};val context=LocalContext.current
 fun picker(value:Long,set:(Long)->Unit){val c=java.util.Calendar.getInstance().apply{timeInMillis=value};android.app.DatePickerDialog(context,{_,y,m,d->set(java.util.Calendar.getInstance().apply{set(y,m,d,9,0,0);set(java.util.Calendar.MILLISECOND,0)}.timeInMillis)},c.get(java.util.Calendar.YEAR),c.get(java.util.Calendar.MONTH),c.get(java.util.Calendar.DAY_OF_MONTH)).show()}
 AlertDialog(onDismissRequest=close,title={Text("Nueva inspección / levantamiento")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(service,{service=it},label={Text("Servicio clínico")});OutlinedTextField(location,{location=it},label={Text("Sala / box / ubicación")});OutlinedTextField(kind,{kind=it},label={Text("Tipo de inspección")});OutlinedTextField(finding,{finding=it},label={Text("Hallazgo")},minLines=2);OutlinedTextField(responsible,{responsible=it},label={Text("Responsable de solución")});Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){OutlinedButton(onClick={picker(date){date=it}}){Text("Inspección: "+hospitalFmt.format(Date(date)))};OutlinedButton(onClick={picker(due){due=it}}){Text("Plazo: "+hospitalFmt.format(Date(due)))}}}},confirmButton={Button(enabled=service.isNotBlank()&&kind.isNotBlank()&&finding.isNotBlank()&&responsible.isNotBlank(),onClick={save(service,location,kind,finding,responsible,date,due)}){Text("Guardar")}},dismissButton={TextButton(onClick=close){Text("Cancelar")}})
}
@Composable fun ReplaceContainerDialog(old:ContainerAsset,close:()->Unit,save:(String,Double?,String,Int,String)->Unit){var kind by remember{mutableStateOf(old.kind)};var cap by remember{mutableStateOf(old.capacityLiters?.toString()?:"")};var color by remember{mutableStateOf(old.color)};var qty by remember{mutableStateOf(old.quantity.toString())};var notes by remember{mutableStateOf("")};AlertDialog(onDismissRequest=close,title={Text("Cambiar contenedor")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text(old.service+" · "+old.location,style=MaterialTheme.typography.titleSmall);Text("Actual: "+old.quantity+" × "+old.kind+(old.capacityLiters?.let{" · "+it+" L"}?:""),color=MaterialTheme.colorScheme.onSurfaceVariant);HorizontalDivider();OutlinedTextField(kind,{kind=it},label={Text("Nuevo tipo")});OutlinedTextField(cap,{cap=it},label={Text("Nueva capacidad (L)")});OutlinedTextField(color,{color=it},label={Text("Color")});OutlinedTextField(qty,{qty=it},label={Text("Cantidad")});OutlinedTextField(notes,{notes=it},label={Text("Motivo / observaciones")},minLines=2)}},confirmButton={Button(enabled=kind.isNotBlank(),onClick={save(kind,cap.toDoubleOrNull(),color,qty.toIntOrNull()?:1,notes)}){Text("Confirmar cambio")}},dismissButton={TextButton(onClick=close){Text("Cancelar")}})}
